export LD_LIBRARY_PATH=/home/drmoser/fvm/build-ubuntu/lib:$LD_LIBRARY_PATH
export PYTHONPATH=/home/drmoser/fvm/build-ubuntu/lib:/home/drmoser/fvm/build-ubuntu/lib64/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/lib/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/bin:/home/drmoser/fvm/build-ubuntu/lib:/home/drmoser/fvm/build-ubuntu/lib64/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/lib/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/bin:/home/drmoser/fvm/build-ubuntu/lib:/home/drmoser/fvm/build-ubuntu/lib64/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/lib/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/bin:/home/drmoser/fvm/build-ubuntu/lib:/home/drmoser/fvm/build-ubuntu/lib64/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/lib/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/bin:/home/drmoser/fvm/build-ubuntu/lib:/home/drmoser/fvm/build-ubuntu/lib64/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/lib/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/bin:/home/drmoser/fvm/build-ubuntu/lib:/home/drmoser/fvm/build-ubuntu/lib64/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/lib/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/bin:/home/drmoser/fvm/build-ubuntu/lib:/home/drmoser/fvm/build-ubuntu/lib64/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/lib/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/bin:/home/drmoser/fvm/build-ubuntu/lib:/home/drmoser/fvm/build-ubuntu/lib64/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/lib/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/bin:/home/drmoser/fvm/build-ubuntu/lib:/home/drmoser/fvm/build-ubuntu/lib64/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/lib/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/bin:/home/drmoser/fvm/build-ubuntu/lib:/home/drmoser/fvm/build-ubuntu/lib64/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/lib/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/bin:/home/drmoser/fvm/build-ubuntu/lib:/home/drmoser/fvm/build-ubuntu/lib64/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/lib/python2.7/site-packages:/home/drmoser/fvm/build-ubuntu/bin
# Add include and lib directories to compiler paths
export C_INCLUDE_PATH=/home/drmoser/fvm/build-ubuntu/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/home/drmoser/fvm/build-ubuntu/include:$CPLUS_INCLUDE_PATH
export PATH=/home/drmoser/fvm/build-ubuntu/bin:$PATH

# Need this to recompile MPM in its directory.
export MEMOSA_CONFNAME=ubuntu
